# Generated by Django 3.1.5 on 2021-01-31 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technologie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(choices=[('JS', 'Javascript'), ('PY', 'Python'), ('HTML', 'Hyper Text Reference Language'), ('CSS', 'Cascading Style Sheets'), ('RCT', 'React Framework'), ('DJO', 'Django Framework'), ('PSQL', 'PostgreSQL DB'), ('MGO', 'Mongo No-SQL DB'), ('OAUT', 'O-authentication'), ('JWT', 'Json Web Tokens'), ('MTZ', 'Materialize Library'), ('BTSP', 'Boostrap Library'), ('SMTC', 'Semantic UI Library'), ('NODE', 'Node.js Runtime Environment'), ('SRG', 'Surge.sh Deployment Platform'), ('HRKU', 'Heroku Deploymeny Platform'), ('PTMN', 'Postman')], default='JS', max_length=4)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.app')),
            ],
        ),
    ]
