# Generated by Django 3.1.5 on 2021-01-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210131_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technologie',
            options={'ordering': ['-tech']},
        ),
        migrations.AlterField(
            model_name='app',
            name='built',
            field=models.CharField(choices=[('B', 'Built'), ('NB', 'Not Built')], default='NB', max_length=2),
        ),
    ]
