# Generated by Django 3.1.5 on 2021-02-02 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210131_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technologie',
            options={},
        ),
        migrations.RemoveField(
            model_name='technologie',
            name='app',
        ),
    ]
