# Generated by Django 3.1.5 on 2021-02-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210202_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='tech',
            field=models.ManyToManyField(to='main_app.Technologie'),
        ),
    ]
