# Generated by Django 3.1.5 on 2021-02-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_app_tech'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologie',
            name='tech',
        ),
        migrations.AddField(
            model_name='technologie',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
